name: Setup action
description: Setup build action
inputs:
  architecture:
    description: 'Target architecture (x64 or x86)'
    required: true
    default: 'x64'
runs:
  using: "composite"
  steps:
    - uses: hustcer/setup-nu@main
      with:
        version: "*"

    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: ${{ inputs.architecture }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Setup depot tools
      uses: 2ndlab/actions/setup-depot-tools@main

    - name: Setup PATH and ENV
      shell: nu {0}
      run: |
        let arch = "${{ inputs.architecture }}"
        [
            $"SkiaSharpName=libSkiaSharp-($env.SkiaSharpVersion)-($env.UCRTVersion)-($arch)"
            $"HarfBuzzSharpName=libHarfBuzzSharp-($env.SkiaSharpVersion)-($env.UCRTVersion)-($arch)"
            $"BuildDir=($env.GITHUB_WORKSPACE)/out/windows/($arch)"
            $"Architecture=($arch)"
        ] | str join (char newline) | save --append $env.GITHUB_ENV
