name: build-skia-2.88.9
on:
  workflow_dispatch:
    inputs:
      architecture:
        description: '构建架构'
        required: true
        type: choice
        options:
          - x64
          - x86
        default: x64
defaults:
  run:
    shell: nu {0}

env:
  SkiaSharpVersion: 2.88.9
jobs:
  build:
    runs-on: windows-2025
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          architecture: ${{ inputs.architecture }}
      - name: Install LLVM 21
        run: winget install --id LLVM.LLVM --accept-package-agreements --accept-source-agreements --disable-interactivity
      - uses: ./.github/actions/build
      - uses: ./.github/actions/deploy
